### ISSUE TITLE
no module named builtins

### ISSUE THREAD

**Issue by Jacob12138xieyuan** [normyx/MMM-Facial-Recognition-OCV3#13]
Traceback (most recent call last):
  File "tools.capture.py", line 9, in <module>
    from lib.tools.capture import ToolsCapture
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 10, in <module>
    from   builtins import input
ImportError: No module named builtins

anyone can help?

**Comment by jesseyofferenvan** [comment]
have you solved this problem? I'm getting the same error then I run  `python tools.capture.py```

**Comment by mhauens** [comment]
I'm also having this problem. :-(

**Comment by mathieugeissler** [comment]
same here

**Comment by atimon** [comment]
i also have this problem, i get: 

> 
Traceback (most recent call last):
  File "tools.capture.py", line 9, in <module>
    from lib.tools.capture import ToolsCapture
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 10, in <module>
    from   builtins import input
ImportError: No module named builtins


>

**Comment by ukcdrf** [comment]
Same here, but it started a little bit earlier when I tried to install the dependencies (following the manual here: https://github.com/normyx/MMM-Facial-Recognition-OCV3)

This part from above documentation worked nicely:
```
Go back to the MMM-Facial-Recognition-OCV3 modules directory :

cd ~/MagicMirror/modules/MMM-Facial-Recognition-OCV3
Install the need dependencies by running the command :

npm install
If you will run the different tools with Python 2.7, install the cross-compatible features with :

```
First issue came up here:
`pip install future`

When I tried to install builtins I recieved this error:

```
Could not install packages due to an EnvironmentError: [Errno 13] Keine Berechtigung: '/usr/local/lib/python3.5/dist-packages/future-0.17.1.dist-info'
Consider using the `--user` option or check the permissions.

```
I solved the missing permissions issue by running:

`sudo pip install future`

However, now when trying to execute the capturing training Python script, I get the same error as reported by the other users above:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-Facial-Recognition-OCV3 $ python tools.capture.py
Traceback (most recent call last):
  File "tools.capture.py", line 9, in <module>
    from lib.tools.capture import ToolsCapture
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 10, in <module>
    from   builtins import input
ImportError: No module named builtins

```
Since this issue is on status "closed" I assume the error *No module named builtins* is solved and I am doing something wrong?
What could it be?

**Comment by ukcdrf** [comment]
Found the solution here:
https://github.com/normyx/MMM-Facial-Recognition-OCV3/issues/29

Now it works  :-)

It is the missing DOT in line 19 of *capture.py* 
`./home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py`

Line 19 shall read like this:
`from .config import ToolsConfig`
